"""Unified CLI entry point for evaluation utilities."""
import argparse
import json
import os
import subprocess
from collections import defaultdict
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

from inference.evaluator import Evaluator
from inference.utils import QUESTION_COLUMN, DATA_PATH
from inference.utils import logging

from .extract_answers import extract_answers

log = logging.getLogger(__name__)
log.setLevel(logging.INFO)


def prepare_input_ifbench(dataset_name: str = "IFBench") -> None:
    """Generate JSONL files for the official IFBench evaluation pipeline.

    This function reads completions from the directory specified by
    `DATA_PATH`, loads the dataset for each model subdirectory, and writes one
    JSONL file per persona configuration in the format the pipeline assumes.

    Args:
        dataset_name (str): Name of the dataset to load through the evaluator. Defaults to "IFBench".

    Raises:
        RuntimeError: If the directory referenced by `DATA_PATH` does not exist.
    """
    log.info("Starting with input preparation")
    load_dotenv()

    data_folder = DATA_PATH
    if not data_folder.exists():
        raise RuntimeError("Data folder does not exist. Please make sure that inference has finished.")

    output_folder = Path("temp/ifbench")
    output_folder.mkdir(exist_ok=True)

    input_path = output_folder / "ifbench_input.jsonl"
    input_written = False
    for model_folder in data_folder.iterdir():
        model_folder_name = model_folder.name
        if not model_folder.is_dir():
            continue

        evaluator = Evaluator(dataset_path=model_folder_name)
        _, df = evaluator.get_data(dataset_name)

        persona_registry = evaluator.get_persona_registry()
        persona_configs = persona_registry.get_configs()

        df["key"] = pd.to_numeric(df["key"])
        df = df.sort_values("key").reset_index(drop=True)

        if not input_written:
            # Create the reference file only once
            with input_path.open("w", encoding="utf-8") as f:
                for row in df.itertuples(index=False):
                    instruction_id_list = getattr(row, "instruction_id_list")
                    kwargs = getattr(row, "kwargs")
                    if hasattr(instruction_id_list, "tolist"):
                        instruction_id_list = instruction_id_list.tolist()
                    if hasattr(kwargs, "tolist"):
                        kwargs = kwargs.tolist()
                    for param in kwargs:
                        for k, v in param.items():
                            if isinstance(v, float):
                                param[k] = int(v)
                    entry = {
                        "key": getattr(row, "key"),
                        "prompt": getattr(row, QUESTION_COLUMN).strip(),
                        "instruction_id_list": instruction_id_list,
                        "kwargs": kwargs,
                    }
                    f.write(json.dumps(entry, ensure_ascii=False) + "\n")
            input_written = True
            log.info("Wrote %s", input_path)
        for persona_cfg in persona_configs:
            persona_name = persona_cfg.name
            answer_column = persona_cfg.answer_column
            if answer_column not in df.columns:
                log.warning("Skipping missing persona column: %s", persona_name)
                continue

            output_path = output_folder / f"{model_folder_name}_{persona_name}.jsonl"
            with output_path.open("w", encoding="utf-8") as f:
                for row in df.itertuples(index=False):
                    response = getattr(row, answer_column)
                    question = getattr(row, QUESTION_COLUMN)
                    entry = {
                        "prompt": question.strip(),
                        "response": response,
                    }
                    f.write(json.dumps(entry, ensure_ascii=False) + "\n")

            log.debug("Wrote %s", output_path)
    log.info("Input preparation finished")


def prepare_df_ifbench(
    input_folder: str | Path = "temp/ifbench/raw",
    output_folder: str = "data/evaluation",
) -> None:
    """Convert raw IFBench evaluation outputs into a consolidated CSV file.

    This function reads JSONL files generated by the IFBench evaluation script,
    extracts model names, personas, and instruction-following scores, and
    aggregates them into a single pandas DataFrame in long format. Only the
    loose evaluation is considered.

    The DataFrame is saved as "ifbench.csv" in the specified output folder.

    Args:
        input_folder (str | Path): Path to the folder containing raw IFBench
            JSONL output files. Defaults to "temp/ifbench/raw".
        output_folder (str, optional): Path to the folder where the resulting
            CSV file will be saved. Defaults to "data/evaluation".

    Raises:
        ValueError: If the input folder does not exist.
    """
    input_folder = Path(input_folder)
    if not input_folder.exists():
        raise ValueError("Input folder could not be found. Please make sure it exists.")

    data = defaultdict(list)
    for file in input_folder.iterdir():
        file_name = file.stem
        if "_loose" not in file_name:
            # only use loose output for evaluation
            continue

        file_name = file_name.replace("_persona-eval_results_loose", "").split("_")
        model, persona = file_name[0], "_".join(file_name[1:])
        with file.open("r", encoding="utf-8") as f:
            for idx, line in enumerate(f):
                obj = json.loads(line)
                data["static_id"].append(f"IFBench_{idx}")
                data["model"].append(model)
                data["persona"].append(persona)
                data["score"].append(int(obj["follow_all_instructions"]))

    output_path = Path(output_folder)
    output_path.mkdir(exist_ok=True, parents=True)
    df = pd.DataFrame(data)
    csv_path = output_path / "ifbench.csv"
    df.to_csv(csv_path)
    log.info("Wrote %s", csv_path)


def run_ifbench(
    eval_root_env: str = "IFBENCH_EVAL_ROOT",
    dataset_name: str = "IFBench",
    df_output_root: str = "data/evaluation",
) -> None:
    """Run the IFBench evaluation pipeline

    This function generates the required IFBench input file, evaluates all
    response JSONL files in the given folder using the official script, and
    consolidates the results into a single CSV in long-format.

    Args:
        eval_root_env (str): Environment variable pointing to the IFBench
            evaluation script root. Defaults to "IFBENCH_EVAL_ROOT".
        dataset_name (str): Name of the dataset to load through the evaluator.
            Defaults to "IFBench".
        df_output_root (str): Folder where the consolidated CSV will be written.
            Defaults to "data/evaluation".

    Raises:
        RuntimeError: If the IFBench evaluation script root is not configured,
            or if the generated input file is missing.
    """
    log.info("Starting IFBench evaluation run")
    load_dotenv()
    value = os.getenv(eval_root_env)
    if value is None:
        raise RuntimeError(
            f"Environment variable {eval_root_env} was not found or is empty. Please set it to the "
            "IFBench evaluation script root."
        )
    eval_root = Path(value).expanduser()
    if not eval_root.exists():
        raise RuntimeError(
            f"Could not locate IFBench evaluation script. Set {eval_root_env} to its root folder."
        )

    responses_root = Path("temp/ifbench")
    output_root = Path("temp/ifbench/raw")
    output_root.mkdir(exist_ok=True, parents=True)

    prepare_input_ifbench(dataset_name=dataset_name)
    benchmark_file = responses_root / "ifbench_input.jsonl"
    if not benchmark_file.exists():
        raise RuntimeError(f"Expected IFBench input file at {benchmark_file}.")
    log.info("Using IFBench input file at %s", benchmark_file)

    for response_file in responses_root.glob("*.jsonl"):
        if response_file == benchmark_file:
            continue
        try:
            cmd = [
                "python3", "-m", "run_eval",
                f"--input_data={benchmark_file.resolve()}",
                f"--input_response_data={response_file.resolve()}",
                f"--output_dir={output_root.resolve()}",
            ]
            log.info("Running IFBench eval on %s", response_file.name)
            subprocess.run(cmd, cwd=eval_root)
        except Exception as e:
            log.error(e)

    prepare_df_ifbench(input_folder=str(output_root), output_folder=df_output_root)
    log.info("IFBench evaluation finished")


def prepare_df(
    dataset_name: str = "mmlu-pro",
    output_folder: str = "data/evaluation",
) -> None:
    """Prepare evaluation DataFrame for standard datasets and write it to CSV.

    Args:
        dataset_name (str): Name of the dataset to load through the evaluator. Defaults to "mmlu-pro".
        output_folder (str, optional): Path to the folder where the resulting
            CSV file will be saved. Defaults to "data/evaluation".

    Raises:
        RuntimeError: If the directory referenced by `DATA_PATH` does not exist.
    """
    log.info("Starting dataframe preparation")
    load_dotenv()

    data_folder = DATA_PATH
    if not data_folder.exists():
        raise RuntimeError("Data folder does not exist. Please make sure that inference has finished.")

    data = []
    for model_folder in data_folder.iterdir():
        model_folder_name = model_folder.name
        if not model_folder.is_dir():
            continue

        evaluator = Evaluator(dataset_path=model_folder_name)
        _, df = evaluator.get_data(dataset_name)

        persona_registry = evaluator.get_persona_registry()
        id_vars = ["static_id", "model"]
        # quick and dirty
        if dataset_name == "flores":
            scoring_columns = persona_registry.get_judgment_columns()
            extracted_columns = [col.replace("_judgment", "") for col in scoring_columns]
            id_vars.append("iso_639_3")
            answer_col = ""
        elif dataset_name == "alpaca":
            scoring_columns = persona_registry.get_judgment_columns()
            extracted_columns = [col.replace("_judgment", "") for col in scoring_columns]
            answer_col = ""
        elif dataset_name == "mmlu-pro":
            scoring_columns = persona_registry.get_answer_columns()
            extracted_columns = [col.replace("_answer", "") for col in scoring_columns]
            id_vars.append("category")
            answer_col = "answer"
        else:
            scoring_columns = persona_registry.get_answer_columns()
            extracted_columns = [col.replace("_answer", "") for col in scoring_columns]
            id_vars.append("subject")
            answer_col = "answers"

        df = extract_answers(df, scoring_columns, dataset_name)
        df["model"] = model_folder_name
        if dataset_name not in ["flores", "alpaca"]:
            for col in extracted_columns:
                df[col] = (df[answer_col] == df[col]).astype(int)
        df = pd.melt(
            df,
            id_vars=id_vars,
            value_vars=extracted_columns,
            var_name="persona",
            value_name="score",
        )
        data.append(df)

    output_path = Path(output_folder)
    output_path.mkdir(exist_ok=True, parents=True)
    result = pd.concat(data, ignore_index=True)
    result = result[result["score"] >= 0]
    csv_path = output_path / f"{dataset_name}.csv"
    result.to_csv(csv_path)
    log.info("Dataframe preparation finished, created %s", csv_path)


def main() -> None:
    """Main entry point."""
    parser = argparse.ArgumentParser(prog="python3 -m evaluate.preparation")
    subparsers = parser.add_subparsers(dest="command", required=True)

    prep_parser = subparsers.add_parser("all", help="Prepare evaluation dataframes.")
    prep_parser.add_argument(
        "--dataset-name",
        default="mmlu-pro",
        help=(
            "Name of the dataset to load via the evaluator. Should be the same as the corresponding"
            "dataset names in the config_dataset.json file. By default, this is \"mmlu-pro\", "
            "\"flores\", \"alpaca\" and \"MATH\". Defaults to %(default)s."
        ),
    )
    prep_parser.add_argument(
        "--df-output-root",
        default="data/evaluation",
        help="Folder where the consolidated csv will be written. Defaults to %(default)s.",
    )

    ifbench_parser = subparsers.add_parser("ifbench", help="Run IFBench evaluation.")
    ifbench_parser.add_argument(
        "--eval-root-env",
        default="IFBENCH_EVAL_ROOT",
        help="Name of the env var pointing to the IFBench evaluation script root. Defaults to %(default)s.",
    )
    ifbench_parser.add_argument(
        "--dataset-name",
        default="IFBench",
        help=(
            "Name of the dataset to load via the evaluator. Make sure this name is equal to the one given to the "
            "IFBench dataset in the config_dataset.json file. Defaults to %(default)s."
        ),
    )
    ifbench_parser.add_argument(
        "--df-output-root",
        default="data/evaluation",
        help="Folder where the consolidated IFBench csv will be written. Defaults to %(default)s.",
    )

    args = parser.parse_args()
    if args.command == "all":
        prepare_df(dataset_name=args.dataset_name, output_folder=args.df_output_root)
    elif args.command == "ifbench":
        run_ifbench(
            eval_root_env=args.eval_root_env,
            dataset_name=args.dataset_name,
            df_output_root=args.df_output_root,
        )
    else:
        parser.error(f"Unknown command: {args.command}")


if __name__ == "__main__":
    main()
